### ISSUE TITLE
Replying back to an email I sent to thread (for followups)

### ISSUE THREAD

**Issue by Simar-Kohli** [resend/resend-node#133]
Hi, 

Sorry in advance if this isn't a correct place to ask this, but I have a use case where I'm looking to send emails via resend, and then followup with emails I've sent. 

How can I accomplish this?

**Comment by vcapretz** [comment]
hi there, for now it's not possible unfortunately, we are looking for ways to expose a message ID in the future that you could use to follow up on messages using thread mechanism, as well as introducing other products that may help with that! 🙏

**Comment by Sohrab-tech1** [comment]
Hey, following up on this — we have the exact same need and have a concrete use case that might help prioritize this.

**Our situation:** 
We send outreach campaigns with automated follow-up sequences (original → follow-up 1 → follow-up 2). Each follow-up needs to thread under the previous email in the recipient's inbox.
                                                                                                                                     
**What we do today:** 
We set In-Reply-To and References headers with synthetic Message-IDs on our own domain (e.g., <uuid@reply.ourdomain.com>). SES preserves these headers even though it overrides Message-ID, so our outbound emails thread correctly with each other.

**Where it breaks:** 
When a recipient replies to one of our emails, their email client sets In-Reply-To to the real SES-assigned

Message-ID (e.g., <hex@email.amazonses.com>). Since Resend never exposes this value, we can't map the reply back to the correct thread or use the real ID in subsequent follow-ups. This causes threading to break in stricter email clients like Outlook/Exchange.

 **What would solve it:** 

**Expose the SES-assigned Message-ID in any of:**
  1. The send response — { "id": "...", "message_id": "<...@email.amazonses.com>" }
  2. The retrieve endpoint — add message_id to GET /emails/:id
  3. Webhook events — include message_id in email.sent / email.delivered payloads

Option 3 is probably most practical since the SES Message-ID may only be known after SES processes the email. From what I can see, the SES Message-ID seems to appear in the Webhook logs, meaning that we should be able to extract the message id from there, store it, and make it available through the API as an endpoint.

This would also make the existing https://resend.com/docs/dashboard/receiving/reply-to-emails docs pattern work end-to-end.

Right now, message_id is only available for inbound emails, but the same value is needed for sent emails to build proper threading chains.

Is this still on the roadmap? Would love to see it happen. 

**Open to contributing if it helps!**
